name: ci
on:
  push:
    branches: ['main', 'releases/**']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Set base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

        # install dependencies for root and all sub packages
      - name: install dependencies
        run: npm ci

      - name: test affected
        run: npx nx affected:test --ci --code-coverage
      - name: lint affected
        run: npx nx affected:lint
      - name: build affected
        run: npx nx affected:build

      - name: bump version
        run: npx semver next-version -w nx -d

      - name: check ts-import-move dist exists
        id: check_ts-import-move_dist
        uses: andstor/file-existence-action@v1
        with:
          files: 'dist/packages/ts-import-move/package.json'

      - name: publish ts-import-move
        if: steps.check_ts-import-move_dist.outputs.files_exists == 'true'
        working-directory: dist/packages/ts-import-move
        run: npm publish --ignore-scripts --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}